# Generated by Django 3.2 on 2021-04-30 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='ids',
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='movies',
            name='genere',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(default='NA', max_length=250),
        ),
    ]
