# Generated by Django 3.2 on 2021-04-30 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210430_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
