# Generated by Django 3.2 on 2021-05-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movies_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
